"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import cosmos.base.v1beta1.coin_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import pocket.shared.service_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Supplier(google.protobuf.message.Message):
    """Supplier represents an actor in Pocket Network that provides RPC services"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OWNER_ADDRESS_FIELD_NUMBER: builtins.int
    OPERATOR_ADDRESS_FIELD_NUMBER: builtins.int
    STAKE_FIELD_NUMBER: builtins.int
    SERVICES_FIELD_NUMBER: builtins.int
    UNSTAKE_SESSION_END_HEIGHT_FIELD_NUMBER: builtins.int
    SERVICE_CONFIG_HISTORY_FIELD_NUMBER: builtins.int
    owner_address: builtins.str
    """Owner address that controls the staked funds and receives rewards by default
    Cannot be updated by the operator
    """
    operator_address: builtins.str
    """Operator address managing the offchain server
    Immutable for supplier's lifespan - requires unstake/re-stake to change.
    Can update supplier configs except for owner address.
    """
    unstake_session_end_height: builtins.int
    """Session end height when supplier initiated unstaking (0 if not unstaking)"""
    @property
    def stake(self) -> cosmos.base.v1beta1.coin_pb2.Coin:
        """Total amount of staked uPOKT"""

    @property
    def services(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[pocket.shared.service_pb2.SupplierServiceConfig]:
        """List of service configurations supported by this supplier"""

    @property
    def service_config_history(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ServiceConfigUpdate]:
        """List of historical service configuration updates, tracking the suppliers
        services update and corresponding activation heights.
        """

    def __init__(
        self,
        *,
        owner_address: builtins.str = ...,
        operator_address: builtins.str = ...,
        stake: cosmos.base.v1beta1.coin_pb2.Coin | None = ...,
        services: collections.abc.Iterable[pocket.shared.service_pb2.SupplierServiceConfig] | None = ...,
        unstake_session_end_height: builtins.int = ...,
        service_config_history: collections.abc.Iterable[global___ServiceConfigUpdate] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["stake", b"stake"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["operator_address", b"operator_address", "owner_address", b"owner_address", "service_config_history", b"service_config_history", "services", b"services", "stake", b"stake", "unstake_session_end_height", b"unstake_session_end_height"]) -> None: ...

global___Supplier = Supplier

@typing.final
class ServiceConfigUpdate(google.protobuf.message.Message):
    """ServiceConfigUpdate tracks a change in a supplier's service configurations
    at a specific block height, enabling tracking of configuration changes over time.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVICES_FIELD_NUMBER: builtins.int
    EFFECTIVE_BLOCK_HEIGHT_FIELD_NUMBER: builtins.int
    effective_block_height: builtins.int
    """Block height at which this service configuration update takes effect,
    aligned with the session start height.
    """
    @property
    def services(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[pocket.shared.service_pb2.SupplierServiceConfig]:
        """List of service configurations after the update was applied."""

    def __init__(
        self,
        *,
        services: collections.abc.Iterable[pocket.shared.service_pb2.SupplierServiceConfig] | None = ...,
        effective_block_height: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["effective_block_height", b"effective_block_height", "services", b"services"]) -> None: ...

global___ServiceConfigUpdate = ServiceConfigUpdate
