# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pocket/shared/supplier.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'pocket/shared/supplier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pocket_clients.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from pocket_clients.proto.cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from pocket_clients.proto.pocket.shared import service_pb2 as pocket_dot_shared_dot_service__pb2
from pocket_clients.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cpocket/shared/supplier.proto\x12\rpocket.shared\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x1bpocket/shared/service.proto\x1a\x14gogoproto/gogo.proto\"\x98\x03\n\x08Supplier\x12=\n\rowner_address\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x0cownerAddress\x12\x43\n\x10operator_address\x18\x02 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x0foperatorAddress\x12/\n\x05stake\x18\x03 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinR\x05stake\x12@\n\x08services\x18\x04 \x03(\x0b\x32$.pocket.shared.SupplierServiceConfigR\x08services\x12;\n\x1aunstake_session_end_height\x18\x05 \x01(\x04R\x17unstakeSessionEndHeight\x12X\n\x16service_config_history\x18\x06 \x03(\x0b\x32\".pocket.shared.ServiceConfigUpdateR\x14serviceConfigHistory\"\x8d\x01\n\x13ServiceConfigUpdate\x12@\n\x08services\x18\x01 \x03(\x0b\x32$.pocket.shared.SupplierServiceConfigR\x08services\x12\x34\n\x16\x65\x66\x66\x65\x63tive_block_height\x18\x02 \x01(\x04R\x14\x65\x66\x66\x65\x63tiveBlockHeightB5Z/github.com/pokt-network/poktroll/x/shared/types\xd8\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pocket.shared.supplier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/pokt-network/poktroll/x/shared/types\330\342\036\001'
  _globals['_SUPPLIER'].fields_by_name['owner_address']._loaded_options = None
  _globals['_SUPPLIER'].fields_by_name['owner_address']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_SUPPLIER'].fields_by_name['operator_address']._loaded_options = None
  _globals['_SUPPLIER'].fields_by_name['operator_address']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_SUPPLIER']._serialized_start=158
  _globals['_SUPPLIER']._serialized_end=566
  _globals['_SERVICECONFIGUPDATE']._serialized_start=569
  _globals['_SERVICECONFIGUPDATE']._serialized_end=710
# @@protoc_insertion_point(module_scope)
