# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pocket/gateway/event.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'pocket/gateway/event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pocket_clients.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from pocket_clients.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from pocket_clients.proto.pocket.gateway import types_pb2 as pocket_dot_gateway_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1apocket/gateway/event.proto\x12\x0epocket.gateway\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a\x1apocket/gateway/types.proto\"\x9a\x01\n\x12\x45ventGatewayStaked\x12>\n\x07gateway\x18\x01 \x01(\x0b\x32\x17.pocket.gateway.GatewayB\x0b\xea\xde\x1f\x07gatewayR\x07gateway\x12\x44\n\x12session_end_height\x18\x02 \x01(\x03\x42\x16\xea\xde\x1f\x12session_end_heightR\x10sessionEndHeight\"\xea\x01\n\x1a\x45ventGatewayUnbondingBegin\x12>\n\x07gateway\x18\x01 \x01(\x0b\x32\x17.pocket.gateway.GatewayB\x0b\xea\xde\x1f\x07gatewayR\x07gateway\x12\x44\n\x12session_end_height\x18\x03 \x01(\x03\x42\x16\xea\xde\x1f\x12session_end_heightR\x10sessionEndHeight\x12\x46\n\x14unbonding_end_height\x18\x04 \x01(\x03\x42\x14\xea\xde\x1f\x10unbonding_heightR\x12unbondingEndHeight\"\xe8\x01\n\x18\x45ventGatewayUnbondingEnd\x12>\n\x07gateway\x18\x01 \x01(\x0b\x32\x17.pocket.gateway.GatewayB\x0b\xea\xde\x1f\x07gatewayR\x07gateway\x12\x44\n\x12session_end_height\x18\x03 \x01(\x03\x42\x16\xea\xde\x1f\x12session_end_heightR\x10sessionEndHeight\x12\x46\n\x14unbonding_end_height\x18\x04 \x01(\x03\x42\x14\xea\xde\x1f\x10unbonding_heightR\x12unbondingEndHeight\"\xa5\x01\n\x1d\x45ventGatewayUnbondingCanceled\x12>\n\x07gateway\x18\x01 \x01(\x0b\x32\x17.pocket.gateway.GatewayB\x0b\xea\xde\x1f\x07gatewayR\x07gateway\x12\x44\n\x12session_end_height\x18\x02 \x01(\x03\x42\x16\xea\xde\x1f\x12session_end_heightR\x10sessionEndHeightB6Z0github.com/pokt-network/poktroll/x/gateway/types\xd8\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pocket.gateway.event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/pokt-network/poktroll/x/gateway/types\330\342\036\001'
  _globals['_EVENTGATEWAYSTAKED'].fields_by_name['gateway']._loaded_options = None
  _globals['_EVENTGATEWAYSTAKED'].fields_by_name['gateway']._serialized_options = b'\352\336\037\007gateway'
  _globals['_EVENTGATEWAYSTAKED'].fields_by_name['session_end_height']._loaded_options = None
  _globals['_EVENTGATEWAYSTAKED'].fields_by_name['session_end_height']._serialized_options = b'\352\336\037\022session_end_height'
  _globals['_EVENTGATEWAYUNBONDINGBEGIN'].fields_by_name['gateway']._loaded_options = None
  _globals['_EVENTGATEWAYUNBONDINGBEGIN'].fields_by_name['gateway']._serialized_options = b'\352\336\037\007gateway'
  _globals['_EVENTGATEWAYUNBONDINGBEGIN'].fields_by_name['session_end_height']._loaded_options = None
  _globals['_EVENTGATEWAYUNBONDINGBEGIN'].fields_by_name['session_end_height']._serialized_options = b'\352\336\037\022session_end_height'
  _globals['_EVENTGATEWAYUNBONDINGBEGIN'].fields_by_name['unbonding_end_height']._loaded_options = None
  _globals['_EVENTGATEWAYUNBONDINGBEGIN'].fields_by_name['unbonding_end_height']._serialized_options = b'\352\336\037\020unbonding_height'
  _globals['_EVENTGATEWAYUNBONDINGEND'].fields_by_name['gateway']._loaded_options = None
  _globals['_EVENTGATEWAYUNBONDINGEND'].fields_by_name['gateway']._serialized_options = b'\352\336\037\007gateway'
  _globals['_EVENTGATEWAYUNBONDINGEND'].fields_by_name['session_end_height']._loaded_options = None
  _globals['_EVENTGATEWAYUNBONDINGEND'].fields_by_name['session_end_height']._serialized_options = b'\352\336\037\022session_end_height'
  _globals['_EVENTGATEWAYUNBONDINGEND'].fields_by_name['unbonding_end_height']._loaded_options = None
  _globals['_EVENTGATEWAYUNBONDINGEND'].fields_by_name['unbonding_end_height']._serialized_options = b'\352\336\037\020unbonding_height'
  _globals['_EVENTGATEWAYUNBONDINGCANCELED'].fields_by_name['gateway']._loaded_options = None
  _globals['_EVENTGATEWAYUNBONDINGCANCELED'].fields_by_name['gateway']._serialized_options = b'\352\336\037\007gateway'
  _globals['_EVENTGATEWAYUNBONDINGCANCELED'].fields_by_name['session_end_height']._loaded_options = None
  _globals['_EVENTGATEWAYUNBONDINGCANCELED'].fields_by_name['session_end_height']._serialized_options = b'\352\336\037\022session_end_height'
  _globals['_EVENTGATEWAYSTAKED']._serialized_start=124
  _globals['_EVENTGATEWAYSTAKED']._serialized_end=278
  _globals['_EVENTGATEWAYUNBONDINGBEGIN']._serialized_start=281
  _globals['_EVENTGATEWAYUNBONDINGBEGIN']._serialized_end=515
  _globals['_EVENTGATEWAYUNBONDINGEND']._serialized_start=518
  _globals['_EVENTGATEWAYUNBONDINGEND']._serialized_end=750
  _globals['_EVENTGATEWAYUNBONDINGCANCELED']._serialized_start=753
  _globals['_EVENTGATEWAYUNBONDINGCANCELED']._serialized_end=918
# @@protoc_insertion_point(module_scope)
