# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pocket/gateway/params.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'pocket/gateway/params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pocket_clients.proto.amino import amino_pb2 as amino_dot_amino__pb2
from pocket_clients.proto.cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from pocket_clients.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bpocket/gateway/params.proto\x12\x0epocket.gateway\x1a\x11\x61mino/amino.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x14gogoproto/gogo.proto\"q\n\x06Params\x12\x45\n\tmin_stake\x18\x01 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\r\xea\xde\x1f\tmin_stakeR\x08minStake: \xe8\xa0\x1f\x01\x8a\xe7\xb0*\x17pocket/x/gateway/ParamsB6Z0github.com/pokt-network/poktroll/x/gateway/types\xd8\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pocket.gateway.params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/pokt-network/poktroll/x/gateway/types\330\342\036\001'
  _globals['_PARAMS'].fields_by_name['min_stake']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['min_stake']._serialized_options = b'\352\336\037\tmin_stake'
  _globals['_PARAMS']._loaded_options = None
  _globals['_PARAMS']._serialized_options = b'\350\240\037\001\212\347\260*\027pocket/x/gateway/Params'
  _globals['_PARAMS']._serialized_start=120
  _globals['_PARAMS']._serialized_end=233
# @@protoc_insertion_point(module_scope)
