# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pocket/gateway/query.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'pocket/gateway/query.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pocket_clients.proto.amino import amino_pb2 as amino_dot_amino__pb2
from pocket_clients.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from pocket_clients.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from pocket_clients.proto.google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from pocket_clients.proto.cosmos.base.query.v1beta1 import pagination_pb2 as cosmos_dot_base_dot_query_dot_v1beta1_dot_pagination__pb2
from pocket_clients.proto.cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from pocket_clients.proto.pocket.gateway import params_pb2 as pocket_dot_gateway_dot_params__pb2
from pocket_clients.proto.pocket.gateway import types_pb2 as pocket_dot_gateway_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1apocket/gateway/query.proto\x12\x0epocket.gateway\x1a\x11\x61mino/amino.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x1bpocket/gateway/params.proto\x1a\x1apocket/gateway/types.proto\"\x14\n\x12QueryParamsRequest\"P\n\x13QueryParamsResponse\x12\x39\n\x06params\x18\x01 \x01(\x0b\x32\x16.pocket.gateway.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\"2\n\x16QueryGetGatewayRequest\x12\x18\n\x07\x61\x64\x64ress\x18\x01 \x01(\tR\x07\x61\x64\x64ress\"R\n\x17QueryGetGatewayResponse\x12\x37\n\x07gateway\x18\x01 \x01(\x0b\x32\x17.pocket.gateway.GatewayB\x04\xc8\xde\x1f\x00R\x07gateway\"a\n\x17QueryAllGatewaysRequest\x12\x46\n\npagination\x18\x01 \x01(\x0b\x32&.cosmos.base.query.v1beta1.PageRequestR\npagination\"\x9e\x01\n\x18QueryAllGatewaysResponse\x12\x39\n\x08gateways\x18\x01 \x03(\x0b\x32\x17.pocket.gateway.GatewayB\x04\xc8\xde\x1f\x00R\x08gateways\x12G\n\npagination\x18\x02 \x01(\x0b\x32\'.cosmos.base.query.v1beta1.PageResponseR\npagination2\xb4\x03\n\x05Query\x12\x80\x01\n\x06Params\x12\".pocket.gateway.QueryParamsRequest\x1a#.pocket.gateway.QueryParamsResponse\"-\x82\xd3\xe4\x93\x02\'\x12%/pokt-network/poktroll/gateway/params\x12\x94\x01\n\x07Gateway\x12&.pocket.gateway.QueryGetGatewayRequest\x1a\'.pocket.gateway.QueryGetGatewayResponse\"8\x82\xd3\xe4\x93\x02\x32\x12\x30/pokt-network/poktroll/gateway/gateway/{address}\x12\x90\x01\n\x0b\x41llGateways\x12\'.pocket.gateway.QueryAllGatewaysRequest\x1a(.pocket.gateway.QueryAllGatewaysResponse\".\x82\xd3\xe4\x93\x02(\x12&/pokt-network/poktroll/gateway/gatewayB6Z0github.com/pokt-network/poktroll/x/gateway/types\xd8\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pocket.gateway.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/pokt-network/poktroll/x/gateway/types\330\342\036\001'
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._loaded_options = None
  _globals['_QUERYPARAMSRESPONSE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_QUERYGETGATEWAYRESPONSE'].fields_by_name['gateway']._loaded_options = None
  _globals['_QUERYGETGATEWAYRESPONSE'].fields_by_name['gateway']._serialized_options = b'\310\336\037\000'
  _globals['_QUERYALLGATEWAYSRESPONSE'].fields_by_name['gateways']._loaded_options = None
  _globals['_QUERYALLGATEWAYSRESPONSE'].fields_by_name['gateways']._serialized_options = b'\310\336\037\000'
  _globals['_QUERY'].methods_by_name['Params']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Params']._serialized_options = b'\202\323\344\223\002\'\022%/pokt-network/poktroll/gateway/params'
  _globals['_QUERY'].methods_by_name['Gateway']._loaded_options = None
  _globals['_QUERY'].methods_by_name['Gateway']._serialized_options = b'\202\323\344\223\0022\0220/pokt-network/poktroll/gateway/gateway/{address}'
  _globals['_QUERY'].methods_by_name['AllGateways']._loaded_options = None
  _globals['_QUERY'].methods_by_name['AllGateways']._serialized_options = b'\202\323\344\223\002(\022&/pokt-network/poktroll/gateway/gateway'
  _globals['_QUERYPARAMSREQUEST']._serialized_start=277
  _globals['_QUERYPARAMSREQUEST']._serialized_end=297
  _globals['_QUERYPARAMSRESPONSE']._serialized_start=299
  _globals['_QUERYPARAMSRESPONSE']._serialized_end=379
  _globals['_QUERYGETGATEWAYREQUEST']._serialized_start=381
  _globals['_QUERYGETGATEWAYREQUEST']._serialized_end=431
  _globals['_QUERYGETGATEWAYRESPONSE']._serialized_start=433
  _globals['_QUERYGETGATEWAYRESPONSE']._serialized_end=515
  _globals['_QUERYALLGATEWAYSREQUEST']._serialized_start=517
  _globals['_QUERYALLGATEWAYSREQUEST']._serialized_end=614
  _globals['_QUERYALLGATEWAYSRESPONSE']._serialized_start=617
  _globals['_QUERYALLGATEWAYSRESPONSE']._serialized_end=775
  _globals['_QUERY']._serialized_start=778
  _globals['_QUERY']._serialized_end=1214
# @@protoc_insertion_point(module_scope)
