"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import cosmos.base.v1beta1.coin_pb2
import google.protobuf.descriptor
import google.protobuf.message
import pocket.application.types_pb2
import pocket.shared.supplier_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class EventImportMorseClaimableAccounts(google.protobuf.message.Message):
    """EventImportMorseClaimableAccounts is emitted when the MorseClaimableAccounts are created on-chain."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREATED_AT_HEIGHT_FIELD_NUMBER: builtins.int
    MORSE_ACCOUNT_STATE_HASH_FIELD_NUMBER: builtins.int
    NUM_ACCOUNTS_FIELD_NUMBER: builtins.int
    created_at_height: builtins.int
    """The height (on Shannon) at which the MorseAccountState was created on-chain."""
    morse_account_state_hash: builtins.bytes
    """The onchain computed sha256 hash of the entire MorseAccountState containing the MorseClaimableAccounts which were imported."""
    num_accounts: builtins.int
    """Number of claimable accounts (EOAs) collected from Morse state export
    NOTE: Account balances include consolidated application and supplier actor stakes
    """
    def __init__(
        self,
        *,
        created_at_height: builtins.int = ...,
        morse_account_state_hash: builtins.bytes = ...,
        num_accounts: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["created_at_height", b"created_at_height", "morse_account_state_hash", b"morse_account_state_hash", "num_accounts", b"num_accounts"]) -> None: ...

global___EventImportMorseClaimableAccounts = EventImportMorseClaimableAccounts

@typing.final
class EventMorseAccountClaimed(google.protobuf.message.Message):
    """EventMorseAccountClaimed is emitted when a MorseAccount is claimed on-chain."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_END_HEIGHT_FIELD_NUMBER: builtins.int
    CLAIMED_BALANCE_FIELD_NUMBER: builtins.int
    SHANNON_DEST_ADDRESS_FIELD_NUMBER: builtins.int
    MORSE_SRC_ADDRESS_FIELD_NUMBER: builtins.int
    session_end_height: builtins.int
    """The session end height (on Shannon) in which the claim was committed (i.e. claimed)."""
    shannon_dest_address: builtins.str
    """The bech32-encoded address of the Shannon account to which the claimed balance will be minted."""
    morse_src_address: builtins.str
    """The hex-encoded address of the Morse account whose balance will be claimed."""
    @property
    def claimed_balance(self) -> cosmos.base.v1beta1.coin_pb2.Coin:
        """The unstaked balance which was claimed."""

    def __init__(
        self,
        *,
        session_end_height: builtins.int = ...,
        claimed_balance: cosmos.base.v1beta1.coin_pb2.Coin | None = ...,
        shannon_dest_address: builtins.str = ...,
        morse_src_address: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["claimed_balance", b"claimed_balance"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["claimed_balance", b"claimed_balance", "morse_src_address", b"morse_src_address", "session_end_height", b"session_end_height", "shannon_dest_address", b"shannon_dest_address"]) -> None: ...

global___EventMorseAccountClaimed = EventMorseAccountClaimed

@typing.final
class EventMorseApplicationClaimed(google.protobuf.message.Message):
    """EventMorseApplicationClaimed is emitted when a MorseAccount is claimed on-chain as a staked application."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_END_HEIGHT_FIELD_NUMBER: builtins.int
    CLAIMED_BALANCE_FIELD_NUMBER: builtins.int
    MORSE_SRC_ADDRESS_FIELD_NUMBER: builtins.int
    CLAIMED_APPLICATION_STAKE_FIELD_NUMBER: builtins.int
    APPLICATION_FIELD_NUMBER: builtins.int
    session_end_height: builtins.int
    """The session end height (on Shannon) in which the claim was committed (i.e. claimed)."""
    morse_src_address: builtins.str
    """The hex-encoded address of the Morse account whose balance will be claimed."""
    @property
    def claimed_balance(self) -> cosmos.base.v1beta1.coin_pb2.Coin:
        """The unstaked balance which was claimed."""

    @property
    def claimed_application_stake(self) -> cosmos.base.v1beta1.coin_pb2.Coin:
        """The stake of the application which was staked as a result of the claim."""

    @property
    def application(self) -> pocket.application.types_pb2.Application:
        """The application which was staked as a result of the claim.
        This is equivalent to the amount it had staked on Morse.
        """

    def __init__(
        self,
        *,
        session_end_height: builtins.int = ...,
        claimed_balance: cosmos.base.v1beta1.coin_pb2.Coin | None = ...,
        morse_src_address: builtins.str = ...,
        claimed_application_stake: cosmos.base.v1beta1.coin_pb2.Coin | None = ...,
        application: pocket.application.types_pb2.Application | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["application", b"application", "claimed_application_stake", b"claimed_application_stake", "claimed_balance", b"claimed_balance"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["application", b"application", "claimed_application_stake", b"claimed_application_stake", "claimed_balance", b"claimed_balance", "morse_src_address", b"morse_src_address", "session_end_height", b"session_end_height"]) -> None: ...

global___EventMorseApplicationClaimed = EventMorseApplicationClaimed

@typing.final
class EventMorseSupplierClaimed(google.protobuf.message.Message):
    """EventMorseSupplierClaimed is emitted when a MorseAccount is claimed on-chain as a staked Supplier."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_END_HEIGHT_FIELD_NUMBER: builtins.int
    CLAIMED_BALANCE_FIELD_NUMBER: builtins.int
    MORSE_SRC_ADDRESS_FIELD_NUMBER: builtins.int
    CLAIMED_SUPPLIER_STAKE_FIELD_NUMBER: builtins.int
    SUPPLIER_FIELD_NUMBER: builtins.int
    session_end_height: builtins.int
    """The session end height (on Shannon) in which the claim was committed (i.e. claimed)."""
    morse_src_address: builtins.str
    """The hex-encoded address of the Morse account whose balance will be claimed."""
    @property
    def claimed_balance(self) -> cosmos.base.v1beta1.coin_pb2.Coin:
        """The unstaked balance which was claimed."""

    @property
    def claimed_supplier_stake(self) -> cosmos.base.v1beta1.coin_pb2.Coin:
        """The stake of the Supplier which was staked as a result of the claim.
        This will be equivalent to the amount it had staked on Morse.
        """

    @property
    def supplier(self) -> pocket.shared.supplier_pb2.Supplier:
        """The Supplier which was staked as a result of the claim."""

    def __init__(
        self,
        *,
        session_end_height: builtins.int = ...,
        claimed_balance: cosmos.base.v1beta1.coin_pb2.Coin | None = ...,
        morse_src_address: builtins.str = ...,
        claimed_supplier_stake: cosmos.base.v1beta1.coin_pb2.Coin | None = ...,
        supplier: pocket.shared.supplier_pb2.Supplier | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["claimed_balance", b"claimed_balance", "claimed_supplier_stake", b"claimed_supplier_stake", "supplier", b"supplier"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["claimed_balance", b"claimed_balance", "claimed_supplier_stake", b"claimed_supplier_stake", "morse_src_address", b"morse_src_address", "session_end_height", b"session_end_height", "supplier", b"supplier"]) -> None: ...

global___EventMorseSupplierClaimed = EventMorseSupplierClaimed
