# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pocket/migration/morse_onchain.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'pocket/migration/morse_onchain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pocket_clients.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from pocket_clients.proto.cosmos.base.v1beta1 import coin_pb2 as cosmos_dot_base_dot_v1beta1_dot_coin__pb2
from pocket_clients.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$pocket/migration/morse_onchain.proto\x12\x10pocket.migration\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x1e\x63osmos/base/v1beta1/coin.proto\x1a\x14gogoproto/gogo.proto\"y\n\x11MorseAccountState\x12\x64\n\x08\x61\x63\x63ounts\x18\x02 \x03(\x0b\x32\'.pocket.migration.MorseClaimableAccountB\x1f\xea\xde\x1f\x08\x61\x63\x63ounts\xf2\xde\x1f\x0fyaml:\"accounts\"R\x08\x61\x63\x63ounts\"\xff\x04\n\x15MorseClaimableAccount\x12\x66\n\x14shannon_dest_address\x18\x01 \x01(\tB4\xc8\xde\x1f\x01\xea\xde\x1f\x14shannon_dest_address\xd2\xb4-\x14\x63osmos.AddressStringR\x12shannonDestAddress\x12\x41\n\x11morse_src_address\x18\x02 \x01(\tB\x15\xea\xde\x1f\x11morse_src_addressR\x0fmorseSrcAddress\x12;\n\npublic_key\x18\x04 \x01(\x0c\x42\x1c\xfa\xde\x1f\x18\x63rypto/ed25519.PublicKeyR\tpublicKey\x12^\n\x10unstaked_balance\x18\x05 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x18\xc8\xde\x1f\x00\xea\xde\x1f\x10unstaked_balanceR\x0funstakedBalance\x12X\n\x0esupplier_stake\x18\x06 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x16\xc8\xde\x1f\x00\xea\xde\x1f\x0esupplier_stakeR\rsupplierStake\x12\x61\n\x11\x61pplication_stake\x18\x07 \x01(\x0b\x32\x19.cosmos.base.v1beta1.CoinB\x19\xc8\xde\x1f\x00\xea\xde\x1f\x11\x61pplication_stakeR\x10\x61pplicationStake\x12\x61\n\x11\x63laimed_at_height\x18\x08 \x01(\x03\x42\x35\xc8\xde\x1f\x01\xea\xde\x1f\x11\x63laimed_at_height\xf2\xde\x1f\x18yaml:\"claimed_at_height\"R\x0f\x63laimedAtHeightB8Z2github.com/pokt-network/poktroll/x/migration/types\xd8\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pocket.migration.morse_onchain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/pokt-network/poktroll/x/migration/types\330\342\036\001'
  _globals['_MORSEACCOUNTSTATE'].fields_by_name['accounts']._loaded_options = None
  _globals['_MORSEACCOUNTSTATE'].fields_by_name['accounts']._serialized_options = b'\352\336\037\010accounts\362\336\037\017yaml:\"accounts\"'
  _globals['_MORSECLAIMABLEACCOUNT'].fields_by_name['shannon_dest_address']._loaded_options = None
  _globals['_MORSECLAIMABLEACCOUNT'].fields_by_name['shannon_dest_address']._serialized_options = b'\310\336\037\001\352\336\037\024shannon_dest_address\322\264-\024cosmos.AddressString'
  _globals['_MORSECLAIMABLEACCOUNT'].fields_by_name['morse_src_address']._loaded_options = None
  _globals['_MORSECLAIMABLEACCOUNT'].fields_by_name['morse_src_address']._serialized_options = b'\352\336\037\021morse_src_address'
  _globals['_MORSECLAIMABLEACCOUNT'].fields_by_name['public_key']._loaded_options = None
  _globals['_MORSECLAIMABLEACCOUNT'].fields_by_name['public_key']._serialized_options = b'\372\336\037\030crypto/ed25519.PublicKey'
  _globals['_MORSECLAIMABLEACCOUNT'].fields_by_name['unstaked_balance']._loaded_options = None
  _globals['_MORSECLAIMABLEACCOUNT'].fields_by_name['unstaked_balance']._serialized_options = b'\310\336\037\000\352\336\037\020unstaked_balance'
  _globals['_MORSECLAIMABLEACCOUNT'].fields_by_name['supplier_stake']._loaded_options = None
  _globals['_MORSECLAIMABLEACCOUNT'].fields_by_name['supplier_stake']._serialized_options = b'\310\336\037\000\352\336\037\016supplier_stake'
  _globals['_MORSECLAIMABLEACCOUNT'].fields_by_name['application_stake']._loaded_options = None
  _globals['_MORSECLAIMABLEACCOUNT'].fields_by_name['application_stake']._serialized_options = b'\310\336\037\000\352\336\037\021application_stake'
  _globals['_MORSECLAIMABLEACCOUNT'].fields_by_name['claimed_at_height']._loaded_options = None
  _globals['_MORSECLAIMABLEACCOUNT'].fields_by_name['claimed_at_height']._serialized_options = b'\310\336\037\001\352\336\037\021claimed_at_height\362\336\037\030yaml:\"claimed_at_height\"'
  _globals['_MORSEACCOUNTSTATE']._serialized_start=139
  _globals['_MORSEACCOUNTSTATE']._serialized_end=260
  _globals['_MORSECLAIMABLEACCOUNT']._serialized_start=263
  _globals['_MORSECLAIMABLEACCOUNT']._serialized_end=902
# @@protoc_insertion_point(module_scope)
