"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Types in this file are ONLY present to facilitate the verifiability of the
migration state from Morse to Shannon.

These types reproduce a 1:1 de/serialization for the corresponding Morse data structures
but are not completely identical to their Morse counterparts, not all of which are defined
as protobuf types in the Morse codebase.

Morse leverages pb.Any types, as well as the gogoproto.casttype option in several places.
All usages of pb.Any have been replaced with equivalent protobuf types
(i.e. an interstitial type with `type` and/or `value` field(s)).
All usages of gogoproto.casttype which previously referenced Morse data structures have been removed.
A few specific fields have retained this option where the type is changed to the underlying
external lib type that the Morse type was wrapping (e.g. address and public key fields).

These types are used by the migration subcommand to transform
the Morse state export into the Shannon state import like so:
 $ pocketd migrate collect-morse-accounts ...

CRITICAL: These types are offchain and ARE NOT persisted onchain (Shannon) at any point.
"""

import builtins
import collections.abc
import cosmos.base.v1beta1.coin_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MorseStateExport(google.protobuf.message.Message):
    """MorseStateExport is the data structure that is serialized and output when running:
     $ pocket utils export-genesis-for-reset ...

    Ref: https://editor.swagger.io/?url=https://raw.githubusercontent.com/pokt-network/pocket-core/staging/doc/specs/rpc-spec.yaml#operations-query-post_query_state
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    APP_HASH_FIELD_NUMBER: builtins.int
    APP_STATE_FIELD_NUMBER: builtins.int
    app_hash: builtins.str
    """app_hash is the Morse tendermint state hash."""
    @property
    def app_state(self) -> global___MorseTendermintAppState:
        """app_state is the entire Morse tendermint application state."""

    def __init__(
        self,
        *,
        app_hash: builtins.str = ...,
        app_state: global___MorseTendermintAppState | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["app_state", b"app_state"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["app_hash", b"app_hash", "app_state", b"app_state"]) -> None: ...

global___MorseStateExport = MorseStateExport

@typing.final
class MorseTendermintAppState(google.protobuf.message.Message):
    """MorseTendermintAppState is the tendermint application state for the Morse tendermint
    application; not to be confused with the pokt protocol actor.
    It is constructed in Morse via `PocketCoreApp#ExportAppState()`.

    See: https://github.com/pokt-network/pocket-core/blob/5fa61920aa9d45ca6bf9e01e863134e242c95fa7/app/pocket.go#L142
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    APPLICATION_FIELD_NUMBER: builtins.int
    AUTH_FIELD_NUMBER: builtins.int
    POS_FIELD_NUMBER: builtins.int
    @property
    def application(self) -> global___MorseApplications: ...
    @property
    def auth(self) -> global___MorseAuth: ...
    @property
    def pos(self) -> global___MorsePos: ...
    def __init__(
        self,
        *,
        application: global___MorseApplications | None = ...,
        auth: global___MorseAuth | None = ...,
        pos: global___MorsePos | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["application", b"application", "auth", b"auth", "pos", b"pos"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["application", b"application", "auth", b"auth", "pos", b"pos"]) -> None: ...

global___MorseTendermintAppState = MorseTendermintAppState

@typing.final
class MorseApplications(google.protobuf.message.Message):
    """A wrapper around the list of MorseApplications, necessary in order to conform to the Morse genesis structure.
    It encapsulates the minimum information required to import Morse applications.

    See: https://github.com/pokt-network/pocket-core/blob/staging/x/apps/types/genesis.go#L4
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    APPLICATIONS_FIELD_NUMBER: builtins.int
    @property
    def applications(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MorseApplication]: ...
    def __init__(
        self,
        *,
        applications: collections.abc.Iterable[global___MorseApplication] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["applications", b"applications"]) -> None: ...

global___MorseApplications = MorseApplications

@typing.final
class MorseAuth(google.protobuf.message.Message):
    """A wrapper around a list of MorseAuthAccount.
    It encapsulates the minimum information required to import Morse accounts.

    See: https://github.com/pokt-network/pocket-core/blob/staging/x/auth/types/genesis.go#L9
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNTS_FIELD_NUMBER: builtins.int
    @property
    def accounts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MorseAuthAccount]: ...
    def __init__(
        self,
        *,
        accounts: collections.abc.Iterable[global___MorseAuthAccount] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["accounts", b"accounts"]) -> None: ...

global___MorseAuth = MorseAuth

@typing.final
class MorseAuthAccount(google.protobuf.message.Message):
    """MorseAccount:
    * Wraps MorseAuthAccount information to conform to Morse genesis structure
    * Represents only externally owned accounts (not module accounts)
    * Avoids pb.Any serialization since only external accounts needed for migration
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    type: builtins.str
    @property
    def value(self) -> global___MorseAccount: ...
    def __init__(
        self,
        *,
        type: builtins.str = ...,
        value: global___MorseAccount | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["type", b"type", "value", b"value"]) -> None: ...

global___MorseAuthAccount = MorseAuthAccount

@typing.final
class MorsePos(google.protobuf.message.Message):
    """A wrapper around the list of Morse suppliers (aka "validators", "nodes", of "servicers").
    It is necessary to conform to the Morse genesis structure.

    See: https://github.com/pokt-network/pocket-core/blob/staging/x/nodes/types/genesis.go#L8
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALIDATORS_FIELD_NUMBER: builtins.int
    @property
    def validators(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MorseValidator]: ...
    def __init__(
        self,
        *,
        validators: collections.abc.Iterable[global___MorseValidator] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["validators", b"validators"]) -> None: ...

global___MorsePos = MorsePos

@typing.final
class MorseApplication(google.protobuf.message.Message):
    """MorseApplication is a subset of the Morse ProtoApplication type.
    It encapsulates the minimum information required to import Morse applications.

    See: https://github.com/pokt-network/pocket-core/blob/staging/proto/x/apps/apps.proto#L16
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    PUBLIC_KEY_FIELD_NUMBER: builtins.int
    JAILED_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    STAKED_TOKENS_FIELD_NUMBER: builtins.int
    address: builtins.bytes
    """Address is a binary representation of the address corresponding
    to a Morse application's ed25519 public key.
    """
    public_key: builtins.bytes
    """PublicKey is the binary representation of a Morse application's ed25519 public key."""
    jailed: builtins.bool
    """TODO_MAINNET_MIGRATION(@Olshansk):  Should status and/or jailed be considered during the migration, and if so, how?"""
    status: builtins.int
    staked_tokens: builtins.str
    """The string representation of the BigInt amount of upokt."""
    def __init__(
        self,
        *,
        address: builtins.bytes = ...,
        public_key: builtins.bytes = ...,
        jailed: builtins.bool = ...,
        status: builtins.int = ...,
        staked_tokens: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "jailed", b"jailed", "public_key", b"public_key", "staked_tokens", b"staked_tokens", "status", b"status"]) -> None: ...

global___MorseApplication = MorseApplication

@typing.final
class MorseValidator(google.protobuf.message.Message):
    """MorseValidator is a subset of the Morse ProtoValidator type.
    It encapsulates the minimum information required to import Morse suppliers (aka "servicers" or "validators").

    See: https://github.com/pokt-network/pocket-core/blob/staging/proto/x/pos/types.proto#L16
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    PUBLIC_KEY_FIELD_NUMBER: builtins.int
    JAILED_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    STAKED_TOKENS_FIELD_NUMBER: builtins.int
    address: builtins.bytes
    """A binary representation of the address corresponding to a Morse application's ed25519 public key."""
    public_key: builtins.bytes
    """The binary representation of a Morse application's ed25519 public key."""
    jailed: builtins.bool
    """TODO_MAINNET_MIGRATION(@Olshansk):  Should status and/or jailed be considered during the migration, and if so, how?"""
    status: builtins.int
    staked_tokens: builtins.str
    """The string representation of the BigInt amount of upokt."""
    def __init__(
        self,
        *,
        address: builtins.bytes = ...,
        public_key: builtins.bytes = ...,
        jailed: builtins.bool = ...,
        status: builtins.int = ...,
        staked_tokens: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "jailed", b"jailed", "public_key", b"public_key", "staked_tokens", b"staked_tokens", "status", b"status"]) -> None: ...

global___MorseValidator = MorseValidator

@typing.final
class MorseAccount(google.protobuf.message.Message):
    """MorseAccount is an analog of the Morse ProtoBaseAccount type.
    It encapsulates the minimum information required to import accounts.

    See: https://github.com/pokt-network/pocket-core/blob/staging/proto/x/auth/auth.proto#L14.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: builtins.int
    PUB_KEY_FIELD_NUMBER: builtins.int
    COINS_FIELD_NUMBER: builtins.int
    address: builtins.bytes
    """A hex-encoded representation of the address corresponding to a Morse application's ed25519 public key."""
    @property
    def pub_key(self) -> global___MorsePublicKey:
        """The ed25519 public key of the account."""

    @property
    def coins(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[cosmos.base.v1beta1.coin_pb2.Coin]:
        """The account balance; this does not include any actor stakes."""

    def __init__(
        self,
        *,
        address: builtins.bytes = ...,
        pub_key: global___MorsePublicKey | None = ...,
        coins: collections.abc.Iterable[cosmos.base.v1beta1.coin_pb2.Coin] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["pub_key", b"pub_key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["address", b"address", "coins", b"coins", "pub_key", b"pub_key"]) -> None: ...

global___MorseAccount = MorseAccount

@typing.final
class MorsePublicKey(google.protobuf.message.Message):
    """MorsePublicKey is required to conform to the encoding of the Morse state export.
    NB: All Morse account public keys will be ed25519 keys by definition.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.bytes
    def __init__(
        self,
        *,
        value: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

global___MorsePublicKey = MorsePublicKey
