# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pocket/migration/params.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'pocket/migration/params.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pocket_clients.proto.amino import amino_pb2 as amino_dot_amino__pb2
from pocket_clients.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dpocket/migration/params.proto\x12\x10pocket.migration\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\"\xad\x01\n\x06Params\x12\x7f\n\x1awaive_morse_claim_gas_fees\x18\x01 \x01(\x08\x42\x43\xea\xde\x1f\x1awaive_morse_claim_gas_fees\xf2\xde\x1f!yaml:\"waive_morse_claim_gas_fees\"R\x16waiveMorseClaimGasFees:\"\xe8\xa0\x1f\x01\x8a\xe7\xb0*\x19pocket/x/migration/ParamsB8Z2github.com/pokt-network/poktroll/x/migration/types\xd8\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pocket.migration.params_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/pokt-network/poktroll/x/migration/types\330\342\036\001'
  _globals['_PARAMS'].fields_by_name['waive_morse_claim_gas_fees']._loaded_options = None
  _globals['_PARAMS'].fields_by_name['waive_morse_claim_gas_fees']._serialized_options = b'\352\336\037\032waive_morse_claim_gas_fees\362\336\037!yaml:\"waive_morse_claim_gas_fees\"'
  _globals['_PARAMS']._loaded_options = None
  _globals['_PARAMS']._serialized_options = b'\350\240\037\001\212\347\260*\031pocket/x/migration/Params'
  _globals['_PARAMS']._serialized_start=93
  _globals['_PARAMS']._serialized_end=266
# @@protoc_insertion_point(module_scope)
