# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pocket/session/tx.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'pocket/session/tx.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pocket_clients.proto.amino import amino_pb2 as amino_dot_amino__pb2
from pocket_clients.proto.cosmos.msg.v1 import msg_pb2 as cosmos_dot_msg_dot_v1_dot_msg__pb2
from pocket_clients.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from pocket_clients.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from pocket_clients.proto.pocket.session import params_pb2 as pocket_dot_session_dot_params__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17pocket/session/tx.proto\x12\x0epocket.session\x1a\x11\x61mino/amino.proto\x1a\x17\x63osmos/msg/v1/msg.proto\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a\x1bpocket/session/params.proto\"\xc3\x01\n\x0fMsgUpdateParams\x12\x36\n\tauthority\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\tauthority\x12\x43\n\x06params\x18\x02 \x01(\x0b\x32\x16.pocket.session.ParamsB\x13\xc8\xde\x1f\x00\xea\xde\x1f\x06params\xa8\xe7\xb0*\x01R\x06params:3\x82\xe7\xb0*\tauthority\x8a\xe7\xb0* pocket/x/session/MsgUpdateParams\"\x19\n\x17MsgUpdateParamsResponse\"\xa5\x01\n\x0eMsgUpdateParam\x12\x36\n\tauthority\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\tauthority\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12,\n\tas_uint64\x18\x03 \x01(\x04\x42\r\xea\xde\x1f\tas_uint64H\x00R\x08\x61sUint64:\x0e\x82\xe7\xb0*\tauthorityB\t\n\x07\x61s_type\"H\n\x16MsgUpdateParamResponse\x12.\n\x06params\x18\x01 \x01(\x0b\x32\x16.pocket.session.ParamsR\x06params2\xbd\x01\n\x03Msg\x12X\n\x0cUpdateParams\x12\x1f.pocket.session.MsgUpdateParams\x1a\'.pocket.session.MsgUpdateParamsResponse\x12U\n\x0bUpdateParam\x12\x1e.pocket.session.MsgUpdateParam\x1a&.pocket.session.MsgUpdateParamResponse\x1a\x05\x80\xe7\xb0*\x01\x42\x36Z0github.com/pokt-network/poktroll/x/session/types\xd8\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pocket.session.tx_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/pokt-network/poktroll/x/session/types\330\342\036\001'
  _globals['_MSGUPDATEPARAMS'].fields_by_name['authority']._loaded_options = None
  _globals['_MSGUPDATEPARAMS'].fields_by_name['authority']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGUPDATEPARAMS'].fields_by_name['params']._loaded_options = None
  _globals['_MSGUPDATEPARAMS'].fields_by_name['params']._serialized_options = b'\310\336\037\000\352\336\037\006params\250\347\260*\001'
  _globals['_MSGUPDATEPARAMS']._loaded_options = None
  _globals['_MSGUPDATEPARAMS']._serialized_options = b'\202\347\260*\tauthority\212\347\260* pocket/x/session/MsgUpdateParams'
  _globals['_MSGUPDATEPARAM'].fields_by_name['authority']._loaded_options = None
  _globals['_MSGUPDATEPARAM'].fields_by_name['authority']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_MSGUPDATEPARAM'].fields_by_name['as_uint64']._loaded_options = None
  _globals['_MSGUPDATEPARAM'].fields_by_name['as_uint64']._serialized_options = b'\352\336\037\tas_uint64'
  _globals['_MSGUPDATEPARAM']._loaded_options = None
  _globals['_MSGUPDATEPARAM']._serialized_options = b'\202\347\260*\tauthority'
  _globals['_MSG']._loaded_options = None
  _globals['_MSG']._serialized_options = b'\200\347\260*\001'
  _globals['_MSGUPDATEPARAMS']._serialized_start=166
  _globals['_MSGUPDATEPARAMS']._serialized_end=361
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_start=363
  _globals['_MSGUPDATEPARAMSRESPONSE']._serialized_end=388
  _globals['_MSGUPDATEPARAM']._serialized_start=391
  _globals['_MSGUPDATEPARAM']._serialized_end=556
  _globals['_MSGUPDATEPARAMRESPONSE']._serialized_start=558
  _globals['_MSGUPDATEPARAMRESPONSE']._serialized_end=630
  _globals['_MSG']._serialized_start=633
  _globals['_MSG']._serialized_end=822
# @@protoc_insertion_point(module_scope)
