# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pocket/session/types.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'pocket/session/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pocket_clients.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from pocket_clients.proto.pocket.shared import service_pb2 as pocket_dot_shared_dot_service__pb2
from pocket_clients.proto.pocket.application import types_pb2 as pocket_dot_application_dot_types__pb2
from pocket_clients.proto.pocket.shared import supplier_pb2 as pocket_dot_shared_dot_supplier__pb2
from pocket_clients.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1apocket/session/types.proto\x12\x0epocket.session\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x1bpocket/shared/service.proto\x1a\x1epocket/application/types.proto\x1a\x1cpocket/shared/supplier.proto\x1a\x14gogoproto/gogo.proto\"\x8e\x02\n\rSessionHeader\x12I\n\x13\x61pplication_address\x18\x01 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x12\x61pplicationAddress\x12\x1d\n\nservice_id\x18\x02 \x01(\tR\tserviceId\x12\x1d\n\nsession_id\x18\x03 \x01(\tR\tsessionId\x12;\n\x1asession_start_block_height\x18\x04 \x01(\x03R\x17sessionStartBlockHeight\x12\x37\n\x18session_end_block_height\x18\x05 \x01(\x03R\x15sessionEndBlockHeight\"\xb5\x02\n\x07Session\x12\x35\n\x06header\x18\x01 \x01(\x0b\x32\x1d.pocket.session.SessionHeaderR\x06header\x12\x1d\n\nsession_id\x18\x02 \x01(\tR\tsessionId\x12%\n\x0esession_number\x18\x03 \x01(\x03R\rsessionNumber\x12\x33\n\x16num_blocks_per_session\x18\x04 \x01(\x03R\x13numBlocksPerSession\x12\x41\n\x0b\x61pplication\x18\x05 \x01(\x0b\x32\x1f.pocket.application.ApplicationR\x0b\x61pplication\x12\x35\n\tsuppliers\x18\x06 \x03(\x0b\x32\x17.pocket.shared.SupplierR\tsuppliersB6Z0github.com/pokt-network/poktroll/x/session/types\xd8\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pocket.session.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/pokt-network/poktroll/x/session/types\330\342\036\001'
  _globals['_SESSIONHEADER'].fields_by_name['application_address']._loaded_options = None
  _globals['_SESSIONHEADER'].fields_by_name['application_address']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_SESSIONHEADER']._serialized_start=187
  _globals['_SESSIONHEADER']._serialized_end=457
  _globals['_SESSION']._serialized_start=460
  _globals['_SESSION']._serialized_end=769
# @@protoc_insertion_point(module_scope)
