# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pocket/service/genesis.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'pocket/service/genesis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pocket_clients.proto.amino import amino_pb2 as amino_dot_amino__pb2
from pocket_clients.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from pocket_clients.proto.pocket.service import params_pb2 as pocket_dot_service_dot_params__pb2
from pocket_clients.proto.pocket.shared import service_pb2 as pocket_dot_shared_dot_service__pb2
from pocket_clients.proto.pocket.service import relay_mining_difficulty_pb2 as pocket_dot_service_dot_relay__mining__difficulty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cpocket/service/genesis.proto\x12\x0epocket.service\x1a\x11\x61mino/amino.proto\x1a\x14gogoproto/gogo.proto\x1a\x1bpocket/service/params.proto\x1a\x1bpocket/shared/service.proto\x1a,pocket/service/relay_mining_difficulty.proto\"\xf5\x01\n\x0cGenesisState\x12\x39\n\x06params\x18\x01 \x01(\x0b\x32\x16.pocket.service.ParamsB\t\xc8\xde\x1f\x00\xa8\xe7\xb0*\x01R\x06params\x12?\n\x0cservice_list\x18\x02 \x03(\x0b\x32\x16.pocket.shared.ServiceB\x04\xc8\xde\x1f\x00R\x0bserviceList\x12i\n\x19relayMiningDifficultyList\x18\x03 \x03(\x0b\x32%.pocket.service.RelayMiningDifficultyB\x04\xc8\xde\x1f\x00R\x19relayMiningDifficultyListB6Z0github.com/pokt-network/poktroll/x/service/types\xd8\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pocket.service.genesis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/pokt-network/poktroll/x/service/types\330\342\036\001'
  _globals['_GENESISSTATE'].fields_by_name['params']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['params']._serialized_options = b'\310\336\037\000\250\347\260*\001'
  _globals['_GENESISSTATE'].fields_by_name['service_list']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['service_list']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE'].fields_by_name['relayMiningDifficultyList']._loaded_options = None
  _globals['_GENESISSTATE'].fields_by_name['relayMiningDifficultyList']._serialized_options = b'\310\336\037\000'
  _globals['_GENESISSTATE']._serialized_start=194
  _globals['_GENESISSTATE']._serialized_end=439
# @@protoc_insertion_point(module_scope)
