# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pocket/service/relay.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'pocket/service/relay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pocket_clients.proto.cosmos_proto import cosmos_pb2 as cosmos__proto_dot_cosmos__pb2
from pocket_clients.proto.gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from pocket_clients.proto.pocket.session import types_pb2 as pocket_dot_session_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1apocket/service/relay.proto\x12\x0epocket.service\x1a\x19\x63osmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\x1a\x1apocket/session/types.proto\"h\n\x05Relay\x12.\n\x03req\x18\x01 \x01(\x0b\x32\x1c.pocket.service.RelayRequestR\x03req\x12/\n\x03res\x18\x02 \x01(\x0b\x32\x1d.pocket.service.RelayResponseR\x03res\"\xd0\x01\n\x14RelayRequestMetadata\x12\x44\n\x0esession_header\x18\x01 \x01(\x0b\x32\x1d.pocket.session.SessionHeaderR\rsessionHeader\x12\x1c\n\tsignature\x18\x02 \x01(\x0cR\tsignature\x12T\n\x19supplier_operator_address\x18\x03 \x01(\tB\x18\xd2\xb4-\x14\x63osmos.AddressStringR\x17supplierOperatorAddress\"h\n\x0cRelayRequest\x12>\n\x04meta\x18\x01 \x01(\x0b\x32$.pocket.service.RelayRequestMetadataB\x04\xc8\xde\x1f\x00R\x04meta\x12\x18\n\x07payload\x18\x02 \x01(\x0cR\x07payload\"j\n\rRelayResponse\x12?\n\x04meta\x18\x01 \x01(\x0b\x32%.pocket.service.RelayResponseMetadataB\x04\xc8\xde\x1f\x00R\x04meta\x12\x18\n\x07payload\x18\x02 \x01(\x0cR\x07payload\"\x9d\x01\n\x15RelayResponseMetadata\x12\x44\n\x0esession_header\x18\x01 \x01(\x0b\x32\x1d.pocket.session.SessionHeaderR\rsessionHeader\x12>\n\x1bsupplier_operator_signature\x18\x02 \x01(\x0cR\x19supplierOperatorSignatureB6Z0github.com/pokt-network/poktroll/x/service/types\xd8\xe2\x1e\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pocket.service.relay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/pokt-network/poktroll/x/service/types\330\342\036\001'
  _globals['_RELAYREQUESTMETADATA'].fields_by_name['supplier_operator_address']._loaded_options = None
  _globals['_RELAYREQUESTMETADATA'].fields_by_name['supplier_operator_address']._serialized_options = b'\322\264-\024cosmos.AddressString'
  _globals['_RELAYREQUEST'].fields_by_name['meta']._loaded_options = None
  _globals['_RELAYREQUEST'].fields_by_name['meta']._serialized_options = b'\310\336\037\000'
  _globals['_RELAYRESPONSE'].fields_by_name['meta']._loaded_options = None
  _globals['_RELAYRESPONSE'].fields_by_name['meta']._serialized_options = b'\310\336\037\000'
  _globals['_RELAY']._serialized_start=123
  _globals['_RELAY']._serialized_end=227
  _globals['_RELAYREQUESTMETADATA']._serialized_start=230
  _globals['_RELAYREQUESTMETADATA']._serialized_end=438
  _globals['_RELAYREQUEST']._serialized_start=440
  _globals['_RELAYREQUEST']._serialized_end=544
  _globals['_RELAYRESPONSE']._serialized_start=546
  _globals['_RELAYRESPONSE']._serialized_end=652
  _globals['_RELAYRESPONSEMETADATA']._serialized_start=655
  _globals['_RELAYRESPONSEMETADATA']._serialized_end=812
# @@protoc_insertion_point(module_scope)
